### ISSUE TITLE
version 3.4.2 is broken

### ISSUE THREAD

**Issue by EugeneElkin** [streamich/memfs#839] opened 2022-05-17 20:13 UTC
Module getBigInt cannot be found!

**Comment by G-Rath** [comment] 2022-05-17 20:14
Duplicate of #837 - please upgrade to v3.4.3

**Closed by G-Rath** 2022-05-17 20:14 UTC

**Comment by EugeneElkin** [comment] 2022-05-17 20:17
Btw, I faced the issue when I update Angular 12  to Angular 13.
I didn't use it directly.
